# Generated by Django 5.0.4 on 2024-05-03 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_summary_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summary',
            name='summary',
            field=models.CharField(max_length=1000),
        ),
    ]
