# Generated by Django 5.0.4 on 2024-05-05 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_summary_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='missionstatement',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
