# Generated by Django 5.0.4 on 2024-05-05 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_missionstatement_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsdescriptions',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='summary',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
