# Generated by Django 5.0.4 on 2024-05-17 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_appsdescriptions_app_gh_url_appsdescriptions_app_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appsdescriptions',
            name='app_gh_url',
            field=models.URLField(default='https://github.com/ZichKoding'),
        ),
    ]
