# Generated by Django 5.0.4 on 2024-05-19 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_alter_appsdescriptions_app_gh_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='appsdescriptions',
            name='app_category',
        ),
        migrations.AddField(
            model_name='appsdescriptions',
            name='app_categories',
            field=models.ManyToManyField(to='portfolio.categories'),
        ),
    ]
